image:
  repository: mcr.microsoft.com/azure-cli
  tag: latest
  pullPolicy: IfNotPresent

replicaNum: 1

namespace: default

demoApp:
  serviceAccountName:

# Helm values configurations for CSI Driver
csi:
  pvName: azure-blob-csi-pv
  pvcName: azure-blob-csi-pvc
  driverName: blob.csi.azure.com
  storageClassName: azureblob-fuse-premium
  mountPath: "/mnt/blob"
  azureResourceGroupName:
  azureStorageAccountName:
  azureBlobContainerName:
  azureStorageIdentityClientID:
